### ISSUE TITLE
Cannot import email addresses

### ISSUE THREAD

**Issue by iprema** [hizzle-co/noptin#111]
**Cannot import email addresses.  Please advise.  I installed your plugin today.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by picocodes** [comment]
Anyone else having this issue please [take a look at this guide](https://noptin.com/guide/getting-email-subscribers/importing-subscribers/).
