### ISSUE TITLE
Subscriber Lists

### ISSUE THREAD

**Issue by gmbhneo** [hizzle-co/noptin#117]
It would be great to have multiple lists of subscribers to send mails to.

For example a test list which you can use to test before sending mails to all subscribers. 
Or a "contributor" list to send only mails to people supporting you.

There are so many use cases where this could come in handy, that's why I think this should really be added. 

Thank you for considering!

**Comment by picocodes** [comment]
Hello, [we already an addon for this](https://noptin.com/product/lists/).
