### ISSUE TITLE
Display all relevant columns on 'Email Subscribers' page

### ISSUE THREAD

**Issue by shawnkhall** [hizzle-co/noptin#156]
**Is your feature request related to a problem? Please describe.**
I'm working on setting up noptin for the first time and I think it should be easier to distinguish different stages and classes of subscribers. 

**Describe the solution you'd like**
Each relevant field in the noptin_subscribers table should be exposed: first, last, email, subscription status, confirmation status, and, ideally, the IP used when signing up - preferably in a table view. Oh, and an *option* to add the IP to the subscription profile (for antispam and validation purposes), along with the ability to use `[[signup_ip]]` (or something similar) within double-opt-in messages and other emails sent by noptin.

**Comment by picocodes** [comment]
Hi @shawnkhall,

The IP address is saved when a customer subscribes to your newsletter ( it's not saved when an admin manually adds a new subscriber or imports subscribers). It can then be displayed in an email via the `[[ip_address]]`.

If you view the profile of a subscriber whose IP address was saved, you will be able to see their IP address and GeoLocation details.

**Comment by shawnkhall** [comment]
Thank you for that. The list at [Email Tags](https://noptin.com/guide/sending-emails/email-tags/) should be updated to include `[[ip_address]]` (and any others that aren't listed there).

My big concern is really that this information *all* be displayed and sortable on the noptin `Email Subscribers` page.

Using other platforms in the past we often had situations where someone would receive a *forwarded* email either from a friend or from an address used in a 'catchall', and doesn't understand why *we* can't unsubscribe them directly using only their email address, or they want to know how we got their email when the email they say they received it at wasn't one that *we* sent to. The only information I may actually have is the unsubscribe link (which gives me the unique subscriber code/confirmation key). There is currently no way to search for that value within the `Email Subscribers` page, and it's not displayed without looking directly at each individual profile. Without going straight to the database this is going to be a hassle. I know "clean" displays are important, but perhaps include an option under the `Screen Options` group to enable or disable display of the other fields (including custom fields).

**Comment by picocodes** [comment]
This will be possible in the next update

![noptin-edit-subscriber-field-configuration](https://user-images.githubusercontent.com/19934448/128365368-1c73c70f-ec4b-4c62-af26-d38a80ed164c.png)
