### ISSUE TITLE
Add List-Unsubscribe headers

### ISSUE THREAD

**Issue by shawnkhall** [hizzle-co/noptin#157]
**Is your feature request related to a problem? Please describe.**
Automated email messages should include List-Unsubscribe headers for ease of removal and compatibility with services like [Gmail](https://support.google.com/mail/answer/81126?hl=en#:~:text=One-click%20Unsubscribe) so they're not treated as spam.

I see a filter within `class-noptin-mailer.php` at `get_headers` to manipulate the headers, but there is no context to populate the unique `[[unsubscribe_url]]` as a header for individual emails. It could be generated at runtime with a query into the subscribers table, but that's not very pretty.

**Describe the solution you'd like**
List-Unsubscribe headers should be added to all messages sent by noptin per [RFC8058](https://tools.ietf.org/html/rfc8058):

    List-Unsubscribe: <[[unsubscribe_url]]>
    List-Unsubscribe-Post: List-Unsubscribe=One-Click

I've tested the unsubscribe URL to ensure it does process correctly with POST. The only thing missing is the email headers.

**Comment by picocodes** [comment]
This is a great idea. I've added the header via https://github.com/hizzle-co/noptin/commit/aa344e986ce9747958c671df626db48c18cf2142

I've also added some context parameters to the hooks fired via the Noptin_Mailer class.
