### ISSUE TITLE
Add nofollow to unsubscribe_url in default email templates

### ISSUE THREAD

**Issue by shawnkhall** [hizzle-co/noptin#158]
**Describe the bug**
The default email templates do not include `nofollow` for the unsubscribe URL. Automated systems on the recipient's email might accidentally trigger an unsubscribe action (GET is not supposed to be used for ["transactional" methods](https://www.ietf.org/rfc/rfc2616.html#section-9.1.1) anyway.)

**Expected behavior**
Any link to actionable URLs should include nofollow to prevent bots from causing problems. 

**Additional context**
The default `permission reminder` is:

`You received this email because you are subscribed to our newsletter. To stop receiving these emails, you can <a href="[[unsubscribe_url]]" target="_blank">unsubscribe</a> at any time.`

It should be:

`You received this email because you are subscribed to our newsletter. To stop receiving these emails, you can <a href="[[unsubscribe_url]]" rel="nofollow" target="_blank">unsubscribe</a> at any time.`

**Comment by picocodes** [comment]
Hi @shawnkhall,

Thanks. I've added the "nofollow" attribute to the unsubscribe link. We use GET because most email clients do not support forms or AJAX. At least one of them is required to use POST.
