### ISSUE TITLE
Add option to change mind with [[resubscribe_url]]

### ISSUE THREAD

**Issue by shawnkhall** [hizzle-co/noptin#159]
**Is your feature request related to a problem? Please describe.**
The `[[unsubscribe_url]]` is a [transactional GET](https://www.ietf.org/rfc/rfc2616.html#section-9.1.1) so there's a chance that it will be clicked and immediately unsubscribe someone when that's not intended by the user.

**Describe the solution you'd like**
It should be possible to more easily resubscribe by just clicking a link on the unsubscribe confirmation page. Ideally, this would come in the form of an optional (nofollow'ed) `[[resubscribe_url]]` merge tag which could be used in the `Unsubscription Message` field.

**Comment by picocodes** [comment]
The [[resubscribe_url]] tag will be available to use in both emails and "subscription success messages" when we release the next update.
