### ISSUE TITLE
[[featured_image]] tag doesn't include featured post picture in resulting email 

### ISSUE THREAD

**Issue by Datospel** [hizzle-co/noptin#160]
**Describe the bug**
[[featured_image]] tag doesn't include featured post picture in resulting email. 

**To Reproduce**

1. Included this tag to Noptin -> Email Campaigns -> Automated Emails -> Automation -> Editor
2. by adding a string: [[featured_image]]
3. Sending Test Email = Email with no featured image of the post. All other infromation and tags filled

![image](https://user-images.githubusercontent.com/10998710/101411367-87188a80-38e9-11eb-9b6e-1aa8d4dd26cd.png)

**Expected behavior**
Expected to see the featured image from the post in email

**Screenshots**
Resulting email:
![image](https://user-images.githubusercontent.com/10998710/101410979-d611f000-38e8-11eb-8eb3-c101865041d0.png)

Post with featured image:
![image](https://user-images.githubusercontent.com/10998710/101411181-34d76980-38e9-11eb-931e-7c585a85e619.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 -  87.0.4280.66

**Additional context**

**Comment by popopopolo** [comment]
I also encounter issue with the tag [[featured_image]], as it doesn't appear at all in the email (I double checked the post in case I forgot to set it). I checked every other available tag, it works, just not the image.
Has anyone looked at Datospel's issue ?

**Comment by picocodes** [comment]
@popopopolo @Datospel  This has been fixed in https://github.com/hizzle-co/noptin/commit/21c211175ea0376e51d7ccd53ec98ce2fcba65ce
