### ISSUE TITLE
Problem with the field

### ISSUE THREAD

**Issue by aprlins** [hizzle-co/noptin#2]
I created an output popup with the plugin of you, in preview it is right, but when entering the site the field to put email and name space appears outside the box, I would like to know why this happened!
Thanks
![popup_viva](https://user-images.githubusercontent.com/55559963/65279794-64902b00-db05-11e9-8a05-42c7060fa030.jpg)

**Comment by picocodes** [comment]
Could you post a link to the page so that I can check it out? Thanks.

**Comment by aprlins** [comment]
Follow the link, thank you very much!
http://novo.vivasa.com.br

Em sex, 20 de set de 2019 às 06:57, picocodes <notifications@github.com>
escreveu:

**Comment by picocodes** [comment]
It is a conflict with your theme. 

Add the following CSS code to your website;

```
.noptin-form-field {
    box-sizing: border-box !important;
}
```

You can either add using the Custom CSS field found in the Theme Customizer or use the custom CSS option found in the form editor.

**Comment by aprlins** [comment]
Now it worked, thank you for your help !!
One more question is not opening on mobile and because of the conflict?
Thanks again!!


Em sex, 20 de set de 2019 às 12:27, picocodes <notifications@github.com>
escreveu:

**Comment by picocodes** [comment]
Popups that are shown when the user is about to leave your website only work on devices that use a mouse or touchpad.

A workaround is to create a new popup, give it a different trigger option then set it to only display on mobile devices.
