### ISSUE TITLE
Manage Subscriptions page

### ISSUE THREAD

**Issue by Terrox** [hizzle-co/noptin#237]
There's no way to unsubscribe without clicking the link from a newsletter. Would be good to have a shortcode or page where you can put in your email address and then unsubscribe, it should send an email confirmation about this too I think in case someone does it maliciously knowing that you won't know about it.

There's an issue with the unsubscribe link for deleted users, maybe it should say "was already unsubscribed". Because it seems like it did something when it didn't, minor issue but a bit wrong.

**Comment by picocodes** [comment]
This is now possible
