### ISSUE TITLE
Confirmation to Unsubscribe

### ISSUE THREAD

**Issue by Terrox** [hizzle-co/noptin#238]
If you click the link accidentally or if your device pre-loads the link or anything similar then you're out of the list and you aren't even aware of it because there's no confirmation message to tell you you've unsubscribed.
Needs both, confirm unsubscription and confirmation email.

**Comment by picocodes** [comment]
We'll add a confirmation button in a future update.

For now, you can set the unsubscription confirmation email using automation rules. Just set "unsubscribed" as the trigger and "send email" as the action.

Also, take a look at https://noptin.com/guide/email-subscribers/unsubscribing/#giving-customers-an-option-to-resubscribe

**Comment by picocodes** [comment]
This won't be implemented. You can [create an unsubscribe form](https://noptin.com/guide/subscription-forms/unsubscribe-forms/) and then replace your unsubscription links with links to the unsubscribe form.
