### ISSUE TITLE
Form hidden for too long with cookie

### ISSUE THREAD

**Issue by Terrox** [hizzle-co/noptin#239]
**Describe the bug**
noptin_hide = true cookie didn't expire.

**To Reproduce**
Not sure what I did, I subscribed I guess.

**Expected behavior**
Cookie should expire after an hour? I logged out of admin and closed tab, reloaded firefox. Cookie survived. Session cookies are not guaranteed to expire on browser close (by design apparently) so you can't really treat them as temporary like most of us devs do (or did)..

**Desktop (please complete the following information):**
Windows 10, Firefox 64 bit

**Comment by picocodes** [comment]
Was researching and found this https://stackoverflow.com/questions/10617954/chrome-doesnt-delete-session-cookies

Seems like we should set the cookie to expire after an hour as you state.

**Comment by picocodes** [comment]
This has been updated for the next update.
