### ISSUE TITLE
Tracking bounced emails

### ISSUE THREAD

**Issue by OWCareers** [hizzle-co/noptin#258]
Noptin is simple and easy to use.

It should also have a feature to manage the bounces. And all bounced emails should be marked as inactive with remarks of bounce code.

Any opponent can crash our website reputation by adding fake emails which will increase bounce rate and will affects our delivery.

I also like to support in the development of this widget. Not sure how, please share your whatsapp number through email.

Regards
Adnan

**Comment by picocodes** [comment]
Hi Adnan,

Noptin does not send the actual emails, so there's no way for us to track bounces. Sending is done via your WordPress install. If you have an SMTP plugin, you can use an automation rule to achieve this:- https://noptin.com/guide/email-subscribers/deleting-bounced-subscribers/
