### ISSUE TITLE
Stats for 'automated emails'?

### ISSUE THREAD

**Issue by KGIII** [hizzle-co/noptin#264]
I'd like to see the stats for "opens" and "clicks" for automated emails.

For example, I have a newsletter that automatically sends out an email whenever there's a new post on my site. I'd like to know how many people opened them and how many people clicked on them.

I do see where this could be a UX problem. How would you show that to the admins that are using the plugin?

My thinking is you can log it somewhere and maybe show the most recent 7 days, 14 days, 28 days, or even let the user configure how long the logs are retained or maybe a maximum log size.

Still, those would make some great numbers to have on-hand. We admins could try some A/B testing to see which types of content are more appealing, for example.

**Comment by picocodes** [comment]
Hi @KGIII,

This is a high priority for us. Here is how we plan on going about solving the issue : 

- You publish a new post.
- We auto-create a normal campaign.
- Then send the campaign to the customer.

That way you can view the stats of each post notification the same way you see the starts for normal campaigns.
Is that going to work for you?

**Comment by KGIII** [comment]
That works for me. Will there be a limit to how many normal campaigns are added, or will we need to prune them manually? (At one post every other day, that'll add up quick.)

Manual pruning isn't too laborious. 

Thanks for responding, by the way. I'll be very interested in seeing how this comes out.

**Comment by picocodes** [comment]
That makes sense. I've also added an option to set the number of days after which sent campaigns should be deleted. We'll release an update on Monday.

The new setting is available at Noptin > Settings > Emails.

![automatically delete campaigns](https://user-images.githubusercontent.com/19934448/118396852-19237c80-b65a-11eb-8c4e-1ed24e573407.png)

**Comment by KGIII** [comment]
I like it! I'm looking forward to it, thanks!

(I'm hoping this doesn't re-open it. I just wanted to thank you.)

**Comment by KGIII** [comment]
Excellent!

Thanks a bunch! If ads ever pay enough, I'll be sure to upgrade.

**Comment by picocodes** [comment]
No problem 😊 did the update solve all your requests?

**Comment by KGIII** [comment]
Solved completely, thanks. Not only did it solve them, it presents the data (and options) in a logical manner. (That's something I'd have had issues with. I wasn't sure how you'd present the data.)

I even was able to test it, as I had a post scheduled for publication the same day the update dropped. I can now see how many people opened it and how many people clicked on it. Fantastic!

I would say this request has been completely resolved, and with incredible speed. I hope other people appreciate the effort and feature as much as I do.
