### ISSUE TITLE
An Essential Featured is Required for WooCommerce.

### ISSUE THREAD

**Issue by sariasaif** [hizzle-co/noptin#317]
As it is stated in Noptin's Website that the plugin is compatible with WooCommerce.
![Screenshot_11](https://user-images.githubusercontent.com/87855361/126763532-cbca9a88-3317-410e-ac1d-edca01fb6486.png)

But sadly I can't find where to create new list of subscribers. Creating lists like (Our Buyers) (Only WordPress Users) (Newsletter Subscribers) etc. 

Maybe I'm failed to deliver what's in my mind, Explore mailpoet for better understanding. Thanks

**Comment by picocodes** [comment]
Kindly explore our add-ons, which allow you to do what you're describing.

https://noptin.com/products/
