### ISSUE TITLE
Latest update has broken the links in the emails.

### ISSUE THREAD

**Issue by KGIII** [hizzle-co/noptin#322]
**Describe the bug**
As the title says, the links don't work. For example, this is a link in the latest newsletter:

https://linux-tips.us/noptin_newsletter/email_click?sid=1&cid=619&noptin_hide=true&to=https%3A%2F%2Flinux-tips.us%2Fweather-in-the-terminal-we-can-do-that%2F

As you can see, that link doesn't work.

**To Reproduce**

Simply update to the newest version. That's 1.5.4 as far as I can see.

**Expected behavior**

I expect the link to work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

It has been this way for the last few notifications, so since the last update - it worked prior.

**Comment by picocodes** [comment]
Seems to be working on all our test sites. Try clearing your permalinks and let us know if that fixes the issue.

**To do this:-**

1. **Step 1:** In the WordPress admin area, go to “Settings > Permalinks”
2. **Step 2:** Click “Save Changes”

![Screen-Recording-2018-04-01-at-03 12-PM](https://user-images.githubusercontent.com/19934448/127721503-0ec19ff3-81dc-4402-af95-dbc1984e7662.gif)

**Comment by KGIII** [comment]
I just want to confirm that it works. I waited until the next article was published (I schedule them) and checked.

Thanks! I have no idea what happened, but that appears to have fixed it.
