### ISSUE TITLE
Bug with Wordpress users dropdown

### ISSUE THREAD

**Issue by megmeg1** [hizzle-co/noptin#335]
**Describe the bug**
Unable to select or search for user roles as the select box is too small and you cannot see the content.

**To Reproduce**
1. Go to  email campaigns and add or edit a campaign
2. Click on send to drop down and select wordpress users

**Expected behavior**
Box should be wider so you can see all content

**Screenshots**
<img width="109" alt="Error with wordpress user" src="https://user-images.githubusercontent.com/62271572/129502627-a824a329-443f-4574-a7da-92a7c33b422a.PNG">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome,
 - Version 92 

**Additional context**
I have deactivated all my custom plugins and it still occurs

**Comment by picocodes** [comment]
This should be fixed now
