### ISSUE TITLE
"Send a test email" seems not working

### ISSUE THREAD

**Issue by iacopy** [hizzle-co/noptin#350]
**Describe the bug**
Recipient does not seem to receive the test email

**To Reproduce**
1. Go to Email Campaigns
2. Click on Edit on a email Draft
2. Edit the Email Content
3. Click on "Sent a test email", enter a valid email address, and then click Send
4. Confirmation popup appears
5. The recipient does not receive the email.

**Expected behavior**
The recipient should receive the test email.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 92.0.4515.159 (Build ufficiale) (x86_64)

**Comment by iacopy** [comment]
@picocodes Thank you. Sure, checking the spam box is the first thing I did.
I see the email with the WP Mail Log plugin, but only with that.
At the end of March it was working.

**Comment by iacopy** [comment]
@picocodes I also tried sending a real newsletter (not simply the test email) by first narrowing down the set of active Subscribers, but they didn't receive anything. So the problem doesn't seem specific to the test mail. On Email Log instead the mails appear.

**Comment by picocodes** [comment]
If the emails appear in your email log then your server is blocking marketing emails from being sent. You might want to sign-up for an SMTP service such as https://sendpulse.com/prices/smtp. They have a free version.
