### ISSUE TITLE
Automatic emails not working properly

### ISSUE THREAD

**Issue by Milati** [hizzle-co/noptin#36]
**Describe the bug**
The automatic emails are not working. Emails are only being send once a new post is made. Not after the original blog post.

**To Reproduce**
1. Create a  blog post
2. No 'new post' email
3. Create another post
4. Email for the original post is send

**Expected behavior**
'New post' email should be sent after the post is made.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by mutendebrian** [comment]
That should not be case. Update to the latest version (1.2.9) and let me know if the issue persists.

In addition,
- Open the automations page and ensure that the automation has been set to run immeadiately a new post is published. You might have set it to wait for a few minutes before it runs.
- Verify that the notifications task is fired on time by clicking on Tools > Schedules actions from the main menu.
![new-post-action-schedule](https://user-images.githubusercontent.com/33359694/81040166-64397a00-8eb3-11ea-8588-c597bcdeb54a.png)
