### ISSUE TITLE
Unable to delete subscriber

### ISSUE THREAD

**Issue by megmeg1** [hizzle-co/noptin#388]
**Describe the bug**
When the delete subscriber is clicked on'page=noptin-subscribers&subscriber=' the confirmation pop appears, Delete is selected and the redirect occurs but the subscriber is still in the main table

**To Reproduce**
1. Go to 'Subscribers'
2. Click on the person you want to edit
3. Select delete from the right hand side bar
4. Select Delete from the pop up- Redirect happens back to main subscribers table for the subscriber is not removed

**Expected behavior**
The subscriber disappears from the subscribers list and is also removed from the data base as a subscriber.

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser = Chrome
 - Version = 97.0.4

**Comment by picocodes** [comment]
Hi @megmeg1,

This bug seems to have been introduced in the last update. We're fixing it now. Thanks for reporting.
