### ISSUE TITLE
"Empty message", after e-mail confirmation

### ISSUE THREAD

**Issue by kardoskrisztina1212** [hizzle-co/noptin#393]
**Describe the bug**
I use the free version of the Noptin plugin. After the subscription, when the user clicks on the Confirmation link, just an empty box appears without a message. (everything works perfectly, just this message is missing)

**To Reproduce**
1. Go to (https://www.demenciaagyakorlatban.com/)
3. Scroll down to the bottom of the page, subscribe and click on the link in the confirmation e-mail.

**Expected behavior**
Show "Successful message, but:
![273810286_1303003806859076_4065522682850244989_n](https://user-images.githubusercontent.com/94357656/153925109-c1198e80-9a7a-48e8-bb37-f23bf82fe5f5.jpg)
"

**Screenshots**
Please find attached the photo.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] firefox: ok

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari] Chrome (example phone screenshot)

**Additional context**

**Comment by picocodes** [comment]
I've finally managed to reproduce this issue and released an update. Thanks.
