### ISSUE TITLE
Optin Newsletter conflict with Wpforms PayPal Plugin

### ISSUE THREAD

**Issue by mexryder** [hizzle-co/noptin#398]
Hello,

Some time ago I installed the Optin Newsletter plugin for Wpforms.

I recently paid for the Pro version of Wpforms to make use of the PayPal plugin, among others.

However, when I create a form and enter the payment section of the PayPal plugin, the entire sheet is completely blank, there is nothing to configure, and therefore I cannot use this functionality.

I contacted Wpforms support and after several steps they determined the following:

"It looks like there might be a conflict between WPForms and Noptin Newsletter, and as you mention just deactivating that plugin seems to resolve the issue.

After doing the troubleshooting with the WP Debugging we didn't find the exact reason for the error, also the console is not showing an error message."

And consequently Wpforms support suggest me two options:

"1. You could reach out to the plugin’s author/support team to share details of the conflict this plugin seems to be causing. They’d hopefully be able to help!

2. I can help you to create a newsletter form in order to get the email addresses and if you wanted to integrate it, you can do it with the following addons: Mailchimp Forms, AWeber Forms, etc."

Having said that, I would very much like to try the first option first, because I really enjoy Optin Newsletter a lot and I found it to be a very good and practical plugin, and that is the reason why I am writing to you. Do you have any solution? How long would it take?

Thanks.

**Comment by picocodes** [comment]
Hi,

Thanks for reporting this. What errors appear in your error log, if any? Could you also please email us a copy of the PayPal add-on to support at noptin dot com so that we can test it?

**Comment by mexryder** [comment]
Thanks for your prompt response.

There are no errors in the log related to this issue.

I am sending you the PayPal plugin to the email address you indicate.

Thanks.

**Comment by picocodes** [comment]
This has been fixed in today's update.

**Comment by mexryder** [comment]
That's right, I noticed, thank you very much.
