### ISSUE TITLE
URL for site image that is inserted onto campains is siteurl.com/home_url

### ISSUE THREAD

**Issue by danielglenn** [hizzle-co/noptin#403]
**Describe the bug**
The logo/image that is automatically inserted in campains has a URL of the site name plus "/home_url". I would remove the image, but there is no where to remove it that I can find.

**To Reproduce**
1. Send a campain
2. Click on the site's logo/image that is automatically inserted at the top
3. You will be taken to the site with the '/home_url' added to the end of the URL

**Expected behavior**
Take me to my site's URL without the '/home_url' and let me remove the image if I want before sending.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: all
 - Version 1.7.1

**Comment by picocodes** [comment]
Hi Daniel,

Thanks for reporting this. We have released a fix for the logo URL.

You can change or remove the logo by clicking on Noptin Newsletter > Settings > Emails then scrolling down to the logo input field.
![add-change-remove-logo](https://user-images.githubusercontent.com/19934448/159859167-5d2b24dd-ccba-41df-be92-a105f04fe857.png)
