### ISSUE TITLE
Alt image option...

### ISSUE THREAD

**Issue by KGIII** [hizzle-co/noptin#406]
Hello, it's me again! Here's a preemptive thanks for reading and considering the following:

To start with, I think it's easiest to describe this with some data.

This is the mail-tester report:

https://www.mail-tester.com/test-ofl3x1csn

Note the penalty for lacking an ALT attributes.

If I take the image out of the newsletter, I score pretty much a perfect 10.

https://www.mail-tester.com/test-mq1chtl0a

The difference between them is *just* a removed logo image. That's the only change between the first and the second set of results.

My thinking was that the system could just add generic ALT attributes - like 'logo' or whatnot. You could probably make them able to be created by the user, but just generic attributes should do - just call it a logo, 'cause that's what it'll be in most cases.

Note: This isn't an image I manually add in the body, it's the Settings > Emails options page.

Why? It's getting more and more difficult for regular people to send email that actually lands in the inbox and not in the spam folder. Removing every barrier to entry seems like a good idea. The ALT attributes could just be a generic 'logo', I should think.

Sure, almost none of your users will even notice the change - but those of us who actually care about this sort of stuff would notice and be grateful. The penalty is pretty small, but probably worthy of consideration.

Again, thanks for reading and considering this.

**Comment by picocodes** [comment]
Hi @KGIII,

Welcome, and thanks for reporting this. [A fix](https://github.com/hizzle-co/noptin/commit/115641d6cf328765d969e09d7284a4db0f8beb29) will be available with the next update.
