### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by megmeg1** [hizzle-co/noptin#443]
**Describe the bug**
1. Spelling mistake in includes\emails\admin\class-newsletter-emails-admin.php
2. Spelling mistake in includes\admin\class-noptin-subscribers-admin.php
Currently:
1. Your email has been added to the sending qeue and will be sent soon.
2. Suscriber added successfully.

Should be:
1. Your email has been added to the sending queue and will be sent soon.
2. Subscriber added successfully.

**Comment by picocodes** [comment]
Thank you @megmeg1 

Both issues will be fixed and an update released today.
