### ISSUE TITLE
Remove jQuery dependancy

### ISSUE THREAD

**Issue by picocodes** [hizzle-co/noptin#497]
### Discussed in https://github.com/hizzle-co/noptin/discussions/496

<div type='discussions-op-text'>

<sup>Originally posted by **picocodes** October 27, 2022</sup>
Forms created using the simple form editor do not depend on jQuery. Let's implement the same for forms created using the advanced form editor.</div>

**Comment by PRO-BROS** [comment]
Yep. I'm also trying to do same for my [site](https://prhocoding.com/)

**Comment by picocodes** [comment]
jQuery is now only loaded when using popup forms
