### ISSUE TITLE
Tags are not stored.

### ISSUE THREAD

**Issue by lasssim** [hizzle-co/noptin#516]
**Describe the bug**
Tags are not stored.

**To Reproduce**

https://user-images.githubusercontent.com/126756/202678769-30c43d89-a075-4a1e-a787-ccd55916f594.mp4

**Expected behavior**
I would expect (as the documentation states) that tags are stored.

**Screenshots**
See video.

**Additional context**
Noptin Version 1.9.3
Noptin Addons Pack 1.7.7
Wordpress 6.1.1

**Comment by picocodes** [comment]
I'm not able to reproduce this on my test site. Could you check your error log in case of a relevant error? In addition, are you on WPEngine or any such WordPress host with aggressive caching?

**Comment by lasssim** [comment]
No, I host WP on my own webspace.

In the chrome dev-tools I noticed that the payload of the `POST` request to `post.php` contains the field for the `noptin-tags` but its value is set to `0`.


![image](https://user-images.githubusercontent.com/126756/202713932-313ac303-171d-4260-b756-f5bc80497e2c.png)

**Comment by lasssim** [comment]
Hmm, strange. I get a warning (See screenshot).

When I try to add a tag, I get the validation error, that the email is not set.

When I add the email address manually again and then add a tag and press update, I get the same behavior as described in the ticket. -> The form reloads, tags are gone.

![image](https://user-images.githubusercontent.com/126756/202722438-32fb0d13-a8e4-4e58-b8a5-2c07427d1310.png)

**Comment by lasssim** [comment]
Btw. the email address is correctly shown in the subscriber list.

**Comment by lasssim** [comment]
Yes they exists.

![image](https://user-images.githubusercontent.com/126756/202796413-d7b5e6fb-bb66-46c2-ae0d-18a90033fd83.png)

This is a snippet from the `subscriber_meta` table:

![image](https://user-images.githubusercontent.com/126756/202796286-8edbeb73-2aa7-4a7b-b17b-279ec624b9aa.png)

**Comment by picocodes** [comment]
Could you please create a temporary admin account and email the details to brian at noptin.com

**Comment by lasssim** [comment]
I dug around a little bit and found out that this line: 

https://github.com/hizzle-co/noptin/blob/e8bd895108328cf127e1f5d2db5699505a958560/includes/admin/class-noptin-subscribers-admin.php#L245 

causes `$subscriber->id` to be set to `0`. 

When I uncomment this line, the form in https://github.com/hizzle-co/noptin/issues/516#issuecomment-1320037626 is rendered as expected (shows email, confirm_key etc.).

**Comment by lasssim** [comment]
Just for fun, I played around with the working **subscriber** form and **added a tag to one subscriber**. I gave the subscriber the tag `this is me` and saving it worked.

Then later, I tried to debug the tag storage issue in the **subscription form view** and I tried to store a tag. The tag `this is me` is working, all other tags can't be stored.




https://user-images.githubusercontent.com/126756/203563085-9d9ce053-2c13-4421-a756-78a047213029.mp4

**Comment by picocodes** [comment]
Strange. I'll take a look once I get back to my computer.

**Comment by lasssim** [comment]
I just updated both plugins and can confirm that the fix works.

Thx a lot!

**Comment by picocodes** [comment]
Thanks for your patience and for pointing us in the right direction.
