### ISSUE TITLE
Post digest does not work properly

### ISSUE THREAD

**Issue by zosoro** [hizzle-co/noptin#517]
So, i want to send a post digest with the post from the last 24 hours. Sadly, the plugin does not undestand this. If i specify to send the email at 10am, it will send ONLY the posts written that day. Not the last 24 hours. 

The only fix i found is to modify newsletter-optin-box/includes/emails/automated-email-types/class-post_digest.php 
to do '-48 hours' instead of  '-1 day'

'after' => gmdate( 'Y-m-d H:i', strtotime( '-48 hours' ) ),

**Comment by picocodes** [comment]
The daily digest sends posts written on the day it sends. I think it's supposed to send the posts written the previous day.

We'll fix it. Thanks.
