### ISSUE TITLE
Lists are not working

### ISSUE THREAD

**Issue by idigIT-onl** [hizzle-co/noptin#519]
Hi there,
When I try to send a Newsletter to a specific list, the newsletter sends the Mail to ALL Subscribers. I tried with the option "Only send to subscribers in a specific lists" and "Do not send to subscribers in a specific lists" - Both ways end up sending newsletter to ALL subscribers.

**To Reproduce**
1. Go to New campaign
2. sent to: Noptin Subscribers
3. Subscription method: Any
4. Lists: "Only send to subscribers in a specific lists" or "Do not send to subscribers in a specific lists" - with checking the lists that should or should not get the Mail

**Expected behavior**
The Newsletter should be send just to the lists that are chosen, or ignore the lists that are not chosen. In both ways, the Newsletter is send to ALL subscribers, ignoring the Lists

**Desktop:**
 - WordPress Version: 6.1.
 - Notpin - WordPress Plugin Version 1.9.0
 - Noptin Addons Pack Version 1.7.5

Thanks!
Regards,
Irena

**Comment by picocodes** [comment]
Hi Irena,

This seems to have been introduced in a recent update. We've released an update (to the Noptin Addons Pack) that fixes it. Thanks for your patience and sorry for the inconvenience caused.
