### ISSUE TITLE
Import of saved CSV file results in skipped entries

### ISSUE THREAD

**Issue by mom2penny** [hizzle-co/noptin#53]
**Describe the bug**
Import of CSV file exported by Noptin plugin results in skipping all entries.

**To Reproduce**
1. Go to Email Subscribers page for plugin
2. Click on Export to export all current subscribers.
3. Save CSV file.
4. Click "Delete All Subscribers"
5. All subscribers will appear to have been removed.
6. Click Import
7. Select CSV that was exported in step 3 above
8 Wait while Ajax import modal window processes CSV file.
9. After CSV file is processed all entries will show as Skipped.

**Expected behavior**
Importing of a saved CSV file should restore deleted entries if they are not duplicates

**Screenshots**
Modal import windows suggests to load web console to see what errors occurred or why entries were skipped. See attached screenshot that does not show any Noptin errors.
<img width="900" alt="Noptin-Console" src="https://user-images.githubusercontent.com/67243573/85236036-d831d200-b3ce-11ea-821c-eecf3dfaf906.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 77.0.1]

**Additional context**
Uninstalling the plugin and manually removing the database tables for the plugin (there is an error in the uninstall script that results in SQL errors) still does not fix the error. We removed the plug, DROPPED the plugin tables from the DB, removed the directories for the plugin from the server and reinstalled the plugin. Oddly even on a fresh install the plugin appears to have stored the newsletter created from a previous install elsewhere in the server as it still appears on a fresh install.

**Comment by picocodes** [comment]
Hi @mom2penny,

How are you?

A record is skipped if one of the following occurs:-
- No email address is detected.
- The email already exists.
- An error occurs when trying to insert the record into the database.

For the first two cases, you can always check the Noptin debug log to see if any of them is the issue. **Noptin > Tools > Debug Log**

However, I think your problem has something to do with your database server. Do send us a copy of the CSV file and the SQL errors (in case you remember them) to support@noptin.com.

**Comment by mom2penny** [comment]
We sent the CSV along with additional screen captures to the email address above.

**Comment by picocodes** [comment]
I'm yet to receive the email. Kindly confirm if you sent it to the right address.

**Comment by mom2penny** [comment]
Hello,

 

I sent it to the correct email address. I just re-sent it. Hopefully that one goes through.

 

Kari

**Comment by picocodes** [comment]
Yeah, I received the second email. Your CSV file did not have any headers so there was no way for Noptin to detect which fields it contained.

I've re-edited it and sent it back to you. It should work now.

Just curious, did you manually remove the headers or did Noptin not include the headers in the file you downloaded?
