### ISSUE TITLE
Image alt Tag could not be added

### ISSUE THREAD

**Issue by KaijuDeluxe** [hizzle-co/noptin#538]
Google page speed claims that there is no image alt tag when using a newsletter form. There is no way to add the missing alt tag.

`form.noptin-optin-form > div.noptin-form-header > div.noptin-form-header-image > img
<img decoding="async" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='…" data-lazy-src="https://cdn.noptin.com/templates/images/email-icon.png"> `

**Comment by picocodes** [comment]
This has been fixed for the next update.

**Comment by KaijuDeluxe** [comment]
Tried to set the new lines of code, but the icon now appears two times. Will that work after the update is released?
<img width="571" alt="image" src="https://user-images.githubusercontent.com/39457956/211462909-56b5af66-9418-4c01-97cd-24f8d5cf1fe4.png">

**Comment by picocodes** [comment]
Replace the contents in **includes/forms/views/legacy/frontend-optin-form.php** with [this](https://raw.githubusercontent.com/hizzle-co/noptin/master/includes/forms/views/legacy/frontend-optin-form.php).
