### ISSUE TITLE
Lists not working when using Templates

### ISSUE THREAD

**Issue by idigIT-onl** [hizzle-co/noptin#546]
Hi, there is still a Problem with the lists not working when using Templates.
I tested it on 2 websites - same ressult.
The installed Version: 
Noptin Version 1.11.1
Addons Pack Version 1.9.0

When I use the Template, I can chose the lists, but they do not aply. After I save the Settings, and go on the Form again, no list is selected.

![grafik](https://user-images.githubusercontent.com/119040422/216764537-3197eb42-fa47-477c-93d2-8701b7e5aa30.png)

There is also no way I can manualy add the users to the lists.
If I go to the Subscriber, set the List I want to subscribe him to, and update, the change is not working. The subscriber is not in the list.

Regards,
Irena

**Comment by picocodes** [comment]
Hi Irena,

I managed to reproduce and fix the issue with lists not saving in the form editor.

However, I'm not able to reproduce the issue with not being able to manually add a subscriber to a list. Could you please install today's update and test again.

**Comment by idigIT-onl** [comment]
Hi!
Thanks for the fast fix. The lists in the editor are now working also.

I am still unable to add an existing subscriber to a list. Sry I think I was not clear enough...
If I go to subscribers -> go to a specific subscriber and than try to assign the subscriber to another list, it doesn't work. When I save it, the changes are not applied. (The subscriber signed up by a form or popup)
![grafik](https://user-images.githubusercontent.com/119040422/216913306-6ca33dc3-b8de-433a-b4af-7d68ade19bbd.png)

If I try to asign a subscriber that was manualy added, it works. Should it be like this, or is it a bug?

Thank you!
Regards,
Irena

**Comment by picocodes** [comment]
No, it should allow you to assign/change lists irrespective of how someone signed up. Are you using any caching plugins?

Also, try changing tags or any other details and let me know if that saves.

**Comment by idigIT-onl** [comment]
There are no caching plugins in use.
Changing any other details works. Just not the subscriber lists.
New discovery: I can assign the subsrcibers to public lists, but not to private lists.
If I change the list to public, I can assign a subscriber to it. When I change it to private, it doesn't work anymore.

Hope this helps. 
Regards,
Irena

**Comment by picocodes** [comment]
Yes, that helps. Testing.

**Comment by picocodes** [comment]
This has been fixed. Please update the addons pack and confirm.

**Comment by idigIT-onl** [comment]
Thank you!
Yes, now it works as it should.
Best regards,
Irena
