### ISSUE TITLE
Email Campaigns Get Stuck

### ISSUE THREAD

**Issue by mexryder** [hizzle-co/noptin#549]
Suddenly, the email campaigns stopped working correctly. The last campaign that worked well was the one on October 31, which was sent to 393 subscribers and is currently in "Sent" status. However, in subsequent campaigns, the emails were not sent to all subscribers. The last one, for example, from January 16, was only sent to 231 subscribers, when I already have more than 400 subscribers, and after almost a month it continues in "Sending" Status, but nothing is progressing anymore. I already tried updating the Plugin and I have the latest version: 1.10.3

OS: Windows 10
Browser: Google Chrome
Wordpress: 6.1.1

**Comment by picocodes** [comment]
Hi,

It seems like a performance plugin deleted the sending batch. We usually sending batches as transients, so if you clear them then sending will pause.

Stop sending the campaign, it will revert to draft, after which you should then click on the send button. Don't worry,  it will only get sent to people who haven't received it.

**Comment by picocodes** [comment]
This should be fixed now.
