### ISSUE TITLE
Integration with WordPress Registration form not working

### ISSUE THREAD

**Issue by daveh551** [hizzle-co/noptin#554]
**Describe the bug**
When I follow the instructions for integrating with the stock WordPress registration forms, I see no change to the registration form displayed (specifically, no checkbox for enabling newsletter subscription). 

**To Reproduce**
1. Go to https://fearofgodbook.com
2. Click on 'Register' in the Meta Widgety
3. 
4. Observe that there is no checkbox for enabling newsletter subscription

**Expected behavior**
When I enable Integration with the WordPress Registration form, then the next time I register a new user, the form should present with a checkbox for enabling subscriptions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave
 - Version Brave version 1.48.158 Chromium version 110.0.5481.77

**Smartphone (please complete the following information):**

**Additional context**

**Comment by picocodes** [comment]
It appears when I visit the registration page on your site.

![Registration-Form-‹-Fear-Of-God-—-WordPress](https://user-images.githubusercontent.com/19934448/218934225-57309bc6-9134-49b5-ad10-7a2241f449b9.png)

**NOTE:** The newsletter checkbox if hidden from existing newsletter subscribers. If that's not what you want, you can change it via Noptin > Settings.

**Comment by daveh551** [comment]
My apologies – I neglected to clear my cache!

 

Dave Hanna

 ***@***.***> ***@***.***

Mobile: +1 (214) 799-6823
