### ISSUE TITLE
email text box turns black on hower unexpectedly at newsletter sign up form ?

### ISSUE THREAD

**Issue by vicjiang78** [hizzle-co/noptin#561]
Hi Sir/Madam, 
I use Noptin newsletter plugin at footer.

but when I tested, moved the mouse to the mail text box,
https://snipboard.io/wdbzxC.jpg

and it will turn black, 
https://snipboard.io/Wg5BGD.jpg

this makes typing an email address difficult. how to fix it?

Best regards,

**Comment by picocodes** [comment]
Hi @vicjiang78, this is most likely a CSS conflict. If you could link to your website then I'll provide custom CSS for you to use.

**Comment by vicjiang78** [comment]
??

https://teaime.com



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/23/2023 22:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [hizzle-co/noptin] email text box turns black on hower unexpectedly at newsletter sign up form ? (Issue #561) |

Hi @vicjiang78, this is most likely a CSS conflict. If you could link to your website then I'll provide custom CSS for you to use.
