### ISSUE TITLE
Automatic "new post"-notifications do not work if the new post is a (modified) clone of an earlier post

### ISSUE THREAD

**Issue by HenkBarreveld** [hizzle-co/noptin#60]
**Describe the bug**
Posts that are created by duplicating an already existing post, are not recognized by Noptin as a new post, so no "new post"-notification is sent on save.

**To Reproduce**
1. Install, activate and configure, for example, the very widely used (>3M installations) WP-plugin Duplicate Post.
2. Open a post in the WP-editor and click "Copy to a new draft" in the admin-bar.
3. Make some changes in the post.
4. Save the post.
-> Result: No notification is sent

**Expected behavior**
Even though you start by making a duplicate of an earlier post, the duplicate is really a new post, so the "new post"-notification should work.

**Additional context**
Analysis: 
The Noptin "new post"-verification is done by checking if the post already has a campaign id assigned. 
In the file includes > automation-rules > class-noptin-new-post-notify.php), the function maybe_send_notification checks if the post already has a key 'noptin_associated_new_post_notification_campaign' in the database table wp_postmeta. If so, it assumes that this is an old post, so the function aborts.

However, when the post is duplicated, the postmeta-values are duplicated as well, therefore the duplicate post already has a campaign id, even though it is new.

So I think this is not the right way to do the "new post"-verification. I did not try this myself, but I think that WordPress offers a native solution in the form of the action hook "transition_post_status". You can use that to verify that the post status is transitioning from ! 'publish' to 'publish'.

By the way, a work-around if you are using the Duplicate Post plugin: in its settings, add 'noptin_associated_new_post_notification_campaign' to the box 'Do not copy these fields".

Good luck! I like your plugin; it has the limited features I want, without the bloat of 'the competition' - and I particularly also like the promise (did not try yet) that you can use your own email templates, or template-less email.

All the best,
Henk

**Comment by picocodes** [comment]
Hi Henk,

Thanks for the detailed post. I'll try to exclude the meta field when a post is duplicated. We actually use the transition_post_status hook, but we also do the further check because using the meta field to prevent a single notification from being sent twice.

For example,

Suppose you publish a post then we send out the new post notification, then later you decide to revert the post to draft. After a while, you re-publish the post again. If we do not use the meta field, your subscribers will be notified twice.

Thanks for reporting this. If you encounter any other bugs, let us know.

**Comment by HenkBarreveld** [comment]
Hi (Brian, isn't it?),

Thank you. Yes, sorry, I see now that you are already using the transition_post_status hook. Don't understand how I missed that.

A solution could be to keep track of post notification details (like post id, campaign id, notification date&time) in a noptin database table instead of the postmeta table -- even though I like your 'small footprint' by using only three database tables (and some data in other tables). MailPoet, for example, creates no less than 30 tables!

I did encounter a few other (supposed) bugs; I will report these as new items.

By the way: what works best for you: reporting in this GitHub repository or on the WordPress support page?

Best regards,
Henk
