### ISSUE TITLE
Subscribers import: Numbers with leading 0 not correctly imported, even if in quotation marks

### ISSUE THREAD

**Issue by g4rf** [hizzle-co/noptin#602]
**Describe the bug**
While importing subscribers via "Import", quoted numbers are imported as normal numbers  and not as text and so loosing their leading zeros.

**To Reproduce**
1. Go to 'Subscribers' and 'Import'
2. Do the import with a CSV with quoted numbers with leading zeros (e.g. German postal codes).
3. Check the imported fields. The leading zeros are gone.

**Expected behavior**
At least when the numbers are quoted, should the imported CSV content be handled as text and no number formatting should be happen.

Thanks in advance,
Jan

**Comment by picocodes** [comment]
I think MySQL strips it out. I'll confirm then fix it as soon as I can.
