### ISSUE TITLE
Dropdown options list not working

### ISSUE THREAD

**Issue by tmsn123** [hizzle-co/noptin#605]
It seems there is a bug in Version 1.11.8 by entering the options for the dropdown select.

If you enter one option per row and then save, the entry is reset afterwards so that all options are in one row. I have tried this several times.

<img width="685" alt="dropdown" src="https://user-images.githubusercontent.com/63092704/234927067-0364701b-985f-4415-938e-da2679516b47.png">

**Comment by picocodes** [comment]
Hi @tmsn123,

This will be fixed in today's update.
