### ISSUE TITLE
Unable send test email

### ISSUE THREAD

**Issue by PsybertronX** [hizzle-co/noptin#648]
### Description

Tested and used successfully for the first time about a month ago, but today using in anger I get error message below when I attempt to send email. Is this a bug or have I just exceeded free use period?

### Screenshots

![NoptinErrorMessage](https://github.com/hizzle-co/noptin/assets/52000402/869a0a29-7c5f-45bf-b92f-2c540a6c6650)

**Comment by picocodes** [comment]
The notice indicates PHP error on your site. You can check your PHP error logs for the exact error message.

**Comment by PsybertronX** [comment]
OK, thanks. I'll see what I can find. Weird though.

**Comment by picocodes** [comment]
Let me know what you find so that I can fix it.

**Comment by PsybertronX** [comment]
Done server reboots, and reinstall of Noptin PlugIn - same problem, with this error report:

An error occurred while sending this campaign. The last error was:
Error
: Uncaught Error: Undefined constant "AUTH_SALT" in /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/includes/functions.php:1453 Stack trace: #0 /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/includes/emails/class-email-type.php(465): noptin_encrypt('{"cid":17522,"s...') #1 /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/includes/emails/class-email-type.php(487): Noptin_Email_Type->before_send(Object(Noptin_Newsletter_Email)) #2 /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/src/Bulk_Emails/Email_Sender_Subscribers.php(94): Noptin_Email_Type->send(Object(Noptin_Newsletter_Email), 17522, 'lucia.lukanova@...') #3 /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/src/Bulk_Emails/Main.php(208): Hizzle\Noptin\Bulk_Emails\Email_Sender_Subscribers->send(Object(Noptin_Newsletter_Email), '22') #4 /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/src/Core/Bulk_Task_Runner.php(120): Hizzle\Noptin\Bulk_Emails\Main->process_task('22') #5 /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/src/Core/Bulk_Task_Runner.php(337): Hizzle\Noptin\Core\Bulk_Task_Runner->run() #6 /home/psybertron/psybertron.org/wp-includes/class-wp-hook.php(308): Hizzle\Noptin\Core\Bulk_Task_Runner->maybe_handle_rescheduled('') #7 /home/psybertron/psybertron.org/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #8 /home/psybertron/psybertron.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #9 /home/psybertron/psybertron.org/wp-admin/admin-ajax.php(188): do_action('wp_ajax_noptin_...') #10 {main} thrown in /home/psybertron/psybertron.org/wp-content/plugins/newsletter-optin-box/includes/functions.php on line 1453

**Comment by picocodes** [comment]
I see. Take a look at this:- https://wordpress.org/support/topic/got-error-php-message-php-warning/
