### ISSUE TITLE
endless mails

### ISSUE THREAD

**Issue by Agomar65** [hizzle-co/noptin#656]
### Description

I've just two subscribers but, when I try to send a simple test campaign, it runs a loop and sends endless mails, I tried to change SMTP plugin but the bug remains the same... Thanks for your support. Agostino

### Additional information

wordpress 6.2.2

WP SMTP plugin or Fluent SMTP as well

Noptin 2.0.0

**Comment by picocodes** [comment]
Hi @Agomar65,

Sorry about that. This bug has now been fixed in Noptin 2.0.1
