### ISSUE TITLE
Failing to Send. Says Sent More Than Total Subscriber Count

### ISSUE THREAD

**Issue by DeanMultimedia** [hizzle-co/noptin#657]
Not in a good mood. I'll try and refrain. Bottom line, apparently part of the process of me sending an important, TIMELY email out to my newsletter requires that I wait for you to respond to a tech support query.

GET ON THIS FAST, PLEASE. This email needs to go out.

1) I duplicated a draft.
2) I created some fresh content in a designated location.
3) I looked through all the fields and clicked "send now".

It sends and sends and sends and sends and ... impressive! Would you look at that? It's managed to "send" to more subscribers THAN I ACTUALLY HAVE!

Which is weird, since I myself am on the list and didn't receive anything. Funny how that works.

This is a time sensitive issue. I look forward to your PROMPT REPLY.

**Comment by DeanMultimedia** [comment]
This just in.

SENT ME HUNDREDS UPON HUNDREDS UPON HUNDREDS IN MY SECOND ATTEMPT.

What used to work, doesn't.

I'm extremely upset. Your code work did this. Not mine.

And I demand a phone call about it.

You've HARMED MY BUSINESS.

**Comment by DeanMultimedia** [comment]
I look forward to a massive apology for this. My current plan is to get a full refund from you and use something I can actually rely on, namely MailPoet.

![screenshot-10](https://github.com/hizzle-co/noptin/assets/46755854/2bfa3adc-451a-4ec9-8b06-49bdd5c4fcce)
![screenshot-11](https://github.com/hizzle-co/noptin/assets/46755854/381d648b-4889-4427-9a04-5accf2a56b6b)
![screenshot-12](https://github.com/hizzle-co/noptin/assets/46755854/35a4dd85-6eb7-4889-8eb3-6619fd65211b)

**Comment by picocodes** [comment]
This has been fixed.
