### ISSUE TITLE
Cannot switch the email template for post notifications

### ISSUE THREAD

**Issue by HenkBarreveld** [hizzle-co/noptin#66]
**Describe the bug**
Choosing a different email template has no effect for post notification messages

**To Reproduce**

1. In the WP dashboard, go to Noptin > Settings > Emails, the email template shows Paste
2. Register a new subscriber: the confirmation email indeed uses the template Paste
3. Publish a new post: The post notification email uses, what seems to be, the Default template
4. Back in Noptin > Settings > Emails, select the Merriweather email template
5. Register a new subscriber: the confirmation email indeed uses the Merriweather template
6. Publish a new post: The post notification email still uses, what seems to be, the Default template

Does the emails setting indeed only affect the confirmation emails? If so, how do I select a template for post notification emails (I don't see it)?

**Comment by picocodes** [comment]
Yeah initially we were manually entering the name of the default template when generating a new post notification. This has been fixed for the next release. All you have to do is [delete this line](https://github.com/hizzle-co/noptin/commit/e97599383246b20aa9673cb5a9840f3a2297eba0#diff-fc31414d9cc6a8f7d1b1b48b21fd3042L319).

**Comment by HenkBarreveld** [comment]
Perfect, thank you!
