### ISSUE TITLE
Email Stats

### ISSUE THREAD

**Issue by joshuafirimjnr** [hizzle-co/noptin#663]
### Description

The email campaigns no longer show stats, even with all settings well. Please fix this.

**Comment by steviem60** [comment]
I had this problem, is this definitely fixed, before I go and send out another mass email and find its not working. lol

**Comment by picocodes** [comment]
It's been fixed but not yet released. We have a release scheduled for Thursday. You can apply this patch to use it right away:- https://github.com/hizzle-co/noptin/commit/f247594dd8bc8212fbd23ba7fdce1b38d4283dbb
