### ISSUE TITLE
"Embed automatically"-option doesn't send email

### ISSUE THREAD

**Issue by GerlindeB** [hizzle-co/noptin#679]
### Description

I have tried for 1 month to get the automatic embedding of the newsletter subscription form to work. So far it was not possible. I don't really know what the problem is. It seems that when I use exactly the same subscription form but only this time with the short-code the automatic email to confirm the email subscription of my newsletter works.

### Screenshots

![image](https://github.com/hizzle-co/noptin/assets/142724227/15291913-0aa6-4700-b735-0340967a1eef)

**Comment by picocodes** [comment]
Are new subscribers created? Let us know if it's only the confirmation emails that are not getting sent.

**Comment by GerlindeB** [comment]
Thanks picocodes for your quick answer.

Some weeks ago the "subscriber"-tab showed "pending". Today I don't even see that in the list, when the subscribers use the "embedded newsletter subscription"-form. On the other hand, when they use the shortcode it seems to work now and the status is "subscribed".

I hope this helps 😊

------- Original Message -------

**Comment by GerlindeB** [comment]
Now noptin decided to also make problems with the shortcode.
Only twice it was possible to successfully subscribe with the shortcode.
Now each subscription leads to the status "pending" and no email is sent whatsoever.

Is this problem known?
Best regards

------- Original Message -------

**Comment by picocodes** [comment]
Test in a private browser window since Noptin hides subscription forms from existing subscribers. You can disable this behavior in your Noptin settings under the **General** tab.
