### ISSUE TITLE
Settings screen is strange.

### ISSUE THREAD

**Issue by takerumaeda** [hizzle-co/noptin#690]
### Description

The settings screen is strange. Please check the attached image.
The version is Noptin - WordPress Newsletter Plugin is Version 2.0.3 and Noptin Addons PackVersion is 2.0.2.

### Screenshots

![2023-09-13_15-50-23](https://github.com/hizzle-co/noptin/assets/104980636/4f7c69b7-e826-4c39-8592-e5d1793fc317)

**Comment by picocodes** [comment]
Hi @takerumaeda,

Seems like our JS/CSS files failed to load. Could you please check your browser's console and let us know if you spot any related errors.

**Comment by takerumaeda** [comment]
![2023-09-20_20-04-52](https://github.com/hizzle-co/noptin/assets/104980636/3b3983ed-f4fd-46aa-8be2-069e830fb11c)
@picocodes Does this make sense?

**Comment by picocodes** [comment]
Yeah, there's an extension on your browser that's preventing our scripts from loading. Try using a different web browser and let me know if the issue persists.

**Comment by takerumaeda** [comment]
It seems that the browser security settings were the cause. Thank you for checking.

----- Original message -----
送信者: picocodes ***@***.***>
宛先: hizzle-co/noptin ***@***.***>
Cc: takerumaeda ***@***.***>, Mention ***@***.***>
件名: Re: [hizzle-co/noptin] Settings screen is strange. (Issue #690)
日付: 2023年9月21日(木曜日) 午後7:05 



Yeah, there's an extension on your browser that's preventing our scripts from loading. Try using a different web browser and let me know if the issue persists.
