### ISSUE TITLE
Pop-Up Form not showing properly

### ISSUE THREAD

**Issue by azkissa** [hizzle-co/noptin#695]
### Description

A Pop-Up Subscription Form is configured as shown by the first three images but it doesn't appear like that on the web page as shown by the fourth image.

### Screenshots

![image](https://github.com/hizzle-co/noptin/assets/145487371/78f91520-4e8e-46d9-8d6b-06f103403a61)
![image](https://github.com/hizzle-co/noptin/assets/145487371/54236822-4df9-4948-a2be-cc480e981de1)
![image](https://github.com/hizzle-co/noptin/assets/145487371/53784e03-847a-401e-b2c2-fc9ceca2205c)

![image](https://github.com/hizzle-co/noptin/assets/145487371/e6aa5d4c-b7b3-4e35-9078-34d4722be1ed)

### Additional information

Website: 
https://staging.happyguttermetalroof.com/

**Comment by picocodes** [comment]
Did you fix this? It works on my end. See screenshot.

![Happy-Gutter-Metal-Roof-–-If-you-are-happy-we-are-happy](https://github.com/hizzle-co/noptin/assets/19934448/a4ace6ba-e148-47e1-9ab6-b0ff040a9b5a)

**Comment by azkissa** [comment]
Thank you for your quick reply. Meanwhile, last night I found the reason:
it was a CSS code I have placed in the Custom CSS.

Best regards.

*Aziz Issá*

MS Office Trainer | Web Designer
Lisboa, Portugal

*Phone*: +351 936 532 684
*Email*: ***@***.***
