### ISSUE TITLE
[FEATURE] Automatically delete Pending Subscribers after X Days

### ISSUE THREAD

**Issue by dhuschde** [hizzle-co/noptin#718]
### Description

I have over 2000 Subscribers in my Database. Only around 30 of which are real. The others are Spam. Deleting them by Hand is very annoying. 

### Describe the solution you'd like

Noptin could delete Pending Subscribers automatically after (for example) 30 Days. 

### Additional information

This should be an opt-in feature.

**Comment by picocodes** [comment]
@dhuschde,

This is possible using an automation rule:- https://noptin.com/guide/email-subscribers/automatically-delete-pending-subscribers/
