### ISSUE TITLE
I upgraded but noptin features aren't working

### ISSUE THREAD

**Issue by kellycr11** [hizzle-co/noptin#744]
I paid to upgrade my plan to send new subscribers emails. It still says I need to upgrade. This is very frustrating and I've tried to contact noptin with no reply. My website is www.generationcedar.com

**Comment by picocodes** [comment]
Hi @kellycr11,

Sorry about that. Please download the addons pack from your account then install it on the site where you need to use the premium features.

Thank you.

**Comment by kellycr11** [comment]
Oh my word! No! When I do that, it gives me only 3 options for creating automated emails. WooCommerce, Send email to my active subscribers, and send to wordpress users. Where did the option for "send welcome email to new subscribers go???"

In His Grip,
Kelly Crawford
<https://www.whiteandlea.com/>

Graphic Designer at Design Jewel<https://www.fiverr.com/designjewel>
Blogger at Generation Cedar<http://www.generationcedar.com/main/>
________________________________

**Comment by picocodes** [comment]
I see. What you're trying to set up is an automated email and you can set it up via **Noptin > Emails Campaigns > Automated Emails > Subscriber Created**.

**Comment by kellycr11** [comment]
Nope, that's where it was before I installed the add ons. These are the only options now. I had to go to "automation rules" to create it.

In His Grip,
Kelly Crawford
<https://www.whiteandlea.com/>

Graphic Designer at Design Jewel<https://www.fiverr.com/designjewel>
Blogger at Generation Cedar<http://www.generationcedar.com/main/>
________________________________
