### ISSUE TITLE
Noptin Pop-up Form Not Working Properly

### ISSUE THREAD

**Issue by donvikii** [hizzle-co/noptin#756]
### Description

After setting the trigger, the pop-up form would work on the next trial and not work again. Sometimes, it doesn't even work. What could be the problem?

**Comment by picocodes** [comment]
Hi @donvikii,

[Try following the instructions here and let me know if that works for you](https://wordpress.org/support/topic/form-doesnt-show-using-the-shortcode/).

**Comment by donvikii** [comment]
I discovered it works well now. Thank you very much.
