### ISSUE TITLE
Transcoding message

### ISSUE THREAD

**Issue by francisfustier** [hizzle-co/noptin#764]
### Description

Since last update there is a transcoding issue in French language in the messages sent. Thank you to fix it. Regards, Francis

### Screenshots

<img width="640" alt="Capture d’écran 2024-02-16 à 11 31 40" src="https://github.com/hizzle-co/noptin/assets/69805736/bc807d19-20b3-4f4a-acf5-edcd72558a9d">

**Comment by picocodes** [comment]
Hi @francisfustier,

Apart from updating Noptin, is there any other change that you made to your site?

**Comment by francisfustier** [comment]
A part usual plugin updates, nothing was changed. Your last release 1.3.01 didn't fix transcoding in French. Seems UTF-8 is not used.
<img width="832" alt="Capture d’écran 2024-02-17 à 16 27 25" src="https://github.com/hizzle-co/noptin/assets/69805736/f60d6b5d-64d3-4bed-b5b6-a192db416bb5">

**Comment by Ralphkh** [comment]
We are facing exactly the same issue. @francisfustier did you manage to solve it?

**Comment by picocodes** [comment]
@francisfustier, @Ralphkh 

I'm still not able to reproduce this, even though I'm using as many special chars as possible in my test.

![scrnli_2_24_2024_7-50-21 AM](https://github.com/hizzle-co/noptin/assets/19934448/310aca33-da16-4c1d-a24a-ad7f6e1dc0bc)

I've tested with all templates and I'm still not able to reproduce this.

Any of you using an email template plugin? Or custom templates? Does the issue persist when you preview the email in your browser or when you send yourself a test email?

**Comment by francisfustier** [comment]
Uploading Enregistrement de l’écran 2024-02-24 à 08.00.29.mov…

**Comment by francisfustier** [comment]
https://github.com/hizzle-co/noptin/assets/69805736/7086ab8c-6ae9-4dca-881f-df303d826444

**Comment by picocodes** [comment]
Are you able to reproduce this on my test site?

**Comment by Ralphkh** [comment]
@picocodes yes when we view in browser we can reproduce this...and when ssnding test emails.
Where can i find your test site?

**Comment by picocodes** [comment]
https://app.instawp.io/wordpress-auto-login?site=%242y%2410%2453ylravfUyORY6eOL9VJSuN0lrK1s.MjqR.WnIceknIrOAFrh9Mhy

**Comment by Ralphkh** [comment]
Hm Indeed on your instance i can t reproduce it. How did you install this noptin version? Updated a previous version or installed from scratch?

**Comment by picocodes** [comment]
I installed the latest version on a new WordPress install. Let me know the list of plugins on your site and I'll test with those.

**Comment by Ralphkh** [comment]
Here are some...
WPML Multilingual CMS
WPForms Lite
WPBakery Page Builder
WP Offload SES Lite
WP Customer Area
Font Awesome
Email Templates
DIMA-Shortcodes
Contact Form 7
Child Theme Configurator
Bookly

**Comment by picocodes** [comment]
Hi @Ralphkh,

There seems to be a conflict with the "Email Templates" plugin. Checking...

For now, you can use one of the templates provided by Noptin instead of selecting "No Template".

NOTE: Noptin allows you to change colors and add custom CSS to the built-in templates. These options will show up when you select one of the built-in templates.

**Comment by francisfustier** [comment]
After update 3.1.0 the preview displays:
![3 1 0](https://github.com/hizzle-co/noptin/assets/69805736/e7c82d5e-1e7e-4f1e-a1b2-a1b780fab640)
