### ISSUE TITLE
Sent newsletters say "[[date]]" instead of the date

### ISSUE THREAD

**Issue by friapro** [hizzle-co/noptin#770]
### Description

I'm sending an automatic post digest email campaign, including the date in the email. It's for months, but suddenly, emails are sent out saying "Newsletter, [[date]]", instead of "Newsletter, 2024-02-19", or similar. This started happening on February 17, and happened again with the digest sent out today. I've checked the Noptin settings, and nothing is changed there. In the Wordpress preview, the date also displays as expected.

What happened? Thank you in advance.

### Screenshots

![Screenshot from 2024-02-19 10-36-52](https://github.com/hizzle-co/noptin/assets/47991303/316574c4-f0f7-413c-bc99-f029a1b283c3)

**Comment by picocodes** [comment]
Hi @friapro,

I've managed to reproduce this. Working on a fix as we speak.

**Comment by picocodes** [comment]
Fixed for today's release
