### ISSUE TITLE
Option to automate sending email not available

### ISSUE THREAD

**Issue by MosheTzvi** [hizzle-co/noptin#775]
### Description

Just installed plugin - when I try to automate an email getting sent on a new post, the drop down for "Select Action" doesn't include an option to send an email.  Just 4 Subscruber related actions.

### Screenshots

![2024-02-22 12_21_33-Add New Automation Rule WordPress](https://github.com/hizzle-co/noptin/assets/109089618/9e40950e-bbbe-45ce-b2ee-098eeb14c340)

**Comment by picocodes** [comment]
Hi @MosheTzvi,

You can set up automated emails via **Noptin > Email Campaigns > Automated Emails > Add New**.

We removed the option to set up automated emails via the automation rules page for better maintainability.
