### ISSUE TITLE
Words are cut when the end of the row is reached

### ISSUE THREAD

**Issue by idigIT-onl** [hizzle-co/noptin#781]
### Description

Hi, since the Update to 3.1.0 I have problems with word wrap in the newsletter. I use the Pro version of Noptin.
As WordPress Theme I use GeneratePress Pro with GenerateBlocks builder. I tried to switch the campaign bulder to classic mode.
With the old Version 2.0.5 everything worked fine.

The words are just cut out and continues in the new row. In the old version, the whole word jumped to the new row.

Thanks!
Best regards,
Irena

**Comment by picocodes** [comment]
Hi @idigIT-onl,

This has been fixed in version 3.1.2. Please update and then send yourself a test email to confirm.
