### ISSUE TITLE
Latest update removes campaign filters for classic editor, and makes difficult to find for block editor

### ISSUE THREAD

**Issue by accunet** [hizzle-co/noptin#785]
### Description

The filters for a digest are now hidden behind the block tab, and hard to find*.  
And are completely gone when using the classic, raw, html editor.

*hard to find, in that you must click in a very small,  specific place in the block editor.  This is not something I'd expect my clients to be able to remember how to do.

### Screenshots

(https://app.screencast.com/fMwt9Ep0oU7GF)

### Additional information
If this is a feature and not a bug... Opinion - please move this back to the primary settings for the newsletter where it was, not hidden under some hard to find block setting.

Thank you!

**Comment by picocodes** [comment]
Hi @accunet,

The block is similar to WordPress's query block. The filters are shown when the parent block is selected. You can select the parent block by clicking on "Posts" in the overview tab.

![scrnli_3_2_2024_6-24-48 AM](https://github.com/hizzle-co/noptin/assets/19934448/9e1359af-5f90-4a75-a71c-1c227fa9bbd0)

We'll definitely add a way to easily access the filters.

**Comment by picocodes** [comment]
The next update will make it easier to find these settings in the block editor. Writers using other editors will still need to manually specify the filters directly in the [[posts]] merge tag.

**Comment by accunet** [comment]
Thanks for your update.

"Writers using other editors will still need to manually specify the filters directly in the [[posts]] merge tag."

So you are completely removing the UI for filtering for Classic editor then, and have no intention to put it back?
