### ISSUE TITLE
I've lost the images from plugin assets/images folder, all broken, as are yours on here?

### ISSUE THREAD

**Issue by terry9873** [hizzle-co/noptin#793]
### Description

We noticed the sign up form on our website suddenly was missing the "email-icon.png" image. Looked and all but two images in that folder are broken, no image. (I am not a dev sorry). 

I found this github page/thing, and browsed to that folder https://github.com/hizzle-co/noptin/tree/master/includes/assets/images

They are all broken too. In my browser you just get a placeholder/broken image. Can someone please advise how to fix this? 

If I go to my hosting server, navigate to that folder, they are all broken there too. Appreciate some advice on how to fix this. (I used ShortPixel to compress and remove unwanted images a week or two ago, wondering if that caused it, or if that's nothing to do with it!) 

Thanks

### Screenshots

![Screenshot 2024-03-04 at 18 33 48](https://github.com/hizzle-co/noptin/assets/77107367/a1287356-d162-4fd7-9098-8a547c42e942)

**Comment by terry9873** [comment]
Asked my host to look into this, they said "Plugin Issue, contact the plugin developer" 
Hoping someone can address this as the images are broken on my site (presumably everyone else's too?)
thanks

**Comment by picocodes** [comment]
Hi @terry9873,

We're looking into this. Thanks.

**Comment by terry9873** [comment]
Thanks, I'd be grateful for an update as soon as you're able to give one. I will need to look at other plugins (which I don't want to be doing!) if it's not likely to be fixed any time soon. 

thanks again

**Comment by picocodes** [comment]
Hi @terry9873,

We've reuploaded the images and will release a plugin update tomorrow. For now, you can edit the form and set your own images.
