### ISSUE TITLE
Unsubscribe link dosn't work anymore

### ISSUE THREAD

**Issue by francisfustier** [hizzle-co/noptin#796]
### Description

With latest version updated, the link is displayed when preview, but not sent

### Screenshots

![Unsubscribe lack](https://github.com/hizzle-co/noptin/assets/69805736/3c51bff5-bfba-4b1d-926b-a559dfadf300)

### Additional information

Noptin V.3.2.0
Wordpress 6.4.3
PHP 8.2

**Comment by picocodes** [comment]
Are other merge tags working on the email?

**Comment by francisfustier** [comment]
As you can see on my third screenshot, all other tags work well.

**Comment by francisfustier** [comment]
The process is only done with Optin built-in features. All subscribers come from Noptin subscription form. The issue appeared with 3.x release, not before. I never change anything in the email form. I don't understand why the [[unsubscrib_url]] is displayed in the preview (2nd screenshot) but not sent in the email (3rd screenshot)?

**Comment by picocodes** [comment]
Hi Francis,

I managed to reproduce and fix the bug via a similar ticket on wp.org. Will release an update today.

Thanks.
