### ISSUE TITLE
The [[read_more_button]]Read More[[/read_more_button]] no longer works.

### ISSUE THREAD

**Issue by KGIII** [hizzle-co/noptin#797]
### Description

Simply, the code to use in emails "[[read_more_button]]Read More[[/read_more_button]]" has stopped working.

I can't be certain when because I'm a slacker. I figured someone would notice and say something but that's my fault. In my defense, I have been pretty busy. I should have reported this sooner, much like I've done previously.

Anyhow, I'm not sure how to expand on that.

It simply doesn't work. I'll grab a screenshot for you.

### Screenshots

![Selection_016](https://github.com/hizzle-co/noptin/assets/13220336/a651b6db-e433-41ae-84a8-9e80477857e5)

### Additional information

I've tried a few ways. I even went so far as to recreate the automated email. I also did that because it quit sending emails, which that cured. This is not a bug reporting that - at this time. This bug is only about the broken read more button.

Aside: It'd be cool if we could adjust the button's color but I digress and may add that as a feature request.

All-in-all, keep up the good work. I've watched this plugin grow a great deal lately and I'm happy to see your success.

The button simply doesn't work. It doesn't work even if they use HTML to read their email. It's broken.

**Comment by picocodes** [comment]
Hi David,

Thanks. Use the following alternative while I look into the above. 

```bash
[[button url="[[post_url]]" text="Continue Reading" background='brand' color='white' rounding='4px']]
```

All arguments are options except the URL and Text arguments. Background="brand" means that the background color should match the brand color that you've set in **Noptin > Settings > Emails**.

**Comment by KGIII** [comment]
Thanks for the tip! I'll give it a shot and I don't think I'd noticed the setting on the Emails section. The plugin has changed a great deal and done so quickly, while I wasn't paying much attention 'cause it just worked.
