### ISSUE TITLE
issue in automated emails

### ISSUE THREAD

**Issue by oekoplatt** [hizzle-co/noptin#81]
Description (as already communicated in https://wordpress.org/support/topic/issue-in-post_excerpt/):

I use manual excerpt and RebelCode’s “WP RSS Aggregator”. 
In automated email Noptin appends the title of an feed to the excerpt.

The original Excerpt is:

Dietmar Bartschs Äußerungen [...] konsequenter Programmatik. (see at https://www.oekologische-plattform.de/)

The campaign is defined as:

   [[post_title]]
   [[post_excerpt]]
   [[read_more_button]]ganzen Beitrag lesen[[/read_more_button]]
   ...

But the received Email contains:

   Aufruf aus der Friedensbewegung (=title)
   Dietmar Bartschs Äußerungen [...] konsequenter Programmatik. (=excerpt)
   ⯈ Späterer Earth-Overshoot-Day öffnet Wege für eine Zukunft innerhalb der 
   Möglichkeiten unseres Planeten 
   <https://www.oekologische-plattform.de/?post_type=wprss_feed_item&p=242033> (= title of an rrs feed, subscribed by RSS Aggregator)
   ganzen Beitrag lesen 
   <https://www.oekologische-plattform.de/2020/09/aufruf-aus-der-friedensbewegung/> (=read_more_button)
   ...

As in the page the excerpt is shown acceptably it should be an Noptin issue.

To Reproduce: Issue occurs only
1. in automated email and
2. if a planned post is published.

[system_information.txt](https://github.com/hizzle-co/noptin/files/5155915/system_information.txt)

**Comment by picocodes** [comment]
Hello @oekoplatt, 

Sorry for the extremely late reply. I've installed the RSS aggregator plugin but was unable to reproduce the issue. It might be related to the settings.

However, I do believe that [this commit fixes](https://github.com/hizzle-co/noptin/commit/026bff2f65a45f3fdbb76caae0aac6e8269d05c6) it.

To test it right away, use the WordPress plugin editor to open the file `"includes\class-noptin-new-post-notify.php"` then replace its contents with [this new code](https://github.com/hizzle-co/noptin/blob/026bff2f65a45f3fdbb76caae0aac6e8269d05c6/includes/class-noptin-new-post-notify.php#L1).
