### ISSUE TITLE
Urgent bug

### ISSUE THREAD

**Issue by JTSTEINMETZ** [hizzle-co/noptin#82]
**Describe the bug**
I am trying to buy your bundle package, but I cannot check out.
I am based in  Hawaii, USA and it tells me I cannot pay because of the State I am located in. Also no paypal or credit card option is available. Is there a reason for this. When clicking on submit it says "invalid payment option" But there was no option in the first place

**To Reproduce**
Go to your online store
Add any product 
go to check out
Payment option and submit payment is not available saying you cannot process payments from my State.
I tried to change the State, even the country and are getting the same message.
I do use paypal and credit card and never had such an issue.

**Expected behavior**
Let me pay and check out and download the premium app

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OS Catalina
 -Tried Chrome, Safari and Firefox

**Additional context**
I sent several support tickets without response over the last 4 days.

**Comment by picocodes** [comment]
Hi @JTSTEINMETZ,

There was an issue with our system but we have resolved it. Sorry for any inconvenience that this may have caused you. Please try again things should work correctly.
