### ISSUE TITLE
Automation rule to send out an email is instead creating hundreds of new products

### ISSUE THREAD

**Issue by PeterBryantDesign** [hizzle-co/noptin#842]
<img width="1539" alt="Screenshot 2024-05-14 at 3 48 56 PM" src="https://github.com/hizzle-co/noptin/assets/167733069/ee3d2000-9e3d-4aa9-90de-37d00b4a5941">
I am hoping this stops when it gets to the 1200 subscribers...

To give some background I setup a automated task to email subscribers the new product when it gets published. I didn't put a delay on the sending of this email when pressing publish and it appeared to time out when publishing (the product did publish). I then went to check if emails were going through and I received one and the log said the automation hadn't run. I then went to check the product and saw that hundreds of new products and continuing to be created and I dont know how to stop it.

See the orphaned content (500+ products and it's still growing by 50 per minute approximately)

**Comment by picocodes** [comment]
Hi @PeterBryantDesign,

Noptin does not support setting up an automation rule that sends emails. You should set up an automated email instead. Please [open a new ticket here](https://support.noptin.com/help/909726194) and a support assistant will guide you through the process of setting this up.

My guess is that you set up an automation rule that creates a new product whenever a product is published, hence the infinite loop.
