### ISSUE TITLE
iPhone Mail App BUG - Newsletter show as blank with no content only in iPhone Mail App.

### ISSUE THREAD

**Issue by Agenda2711** [hizzle-co/noptin#848]
### Description

Hi, I have found a bug in the newsletter. When sending newsletter using the visual composer they are all delivered correctly to Gmail, and other email accounts, and can be viewed correctly directly inside Gmail, outlook, Thunderbird, Apple Mail app on desktops, Android, BUT, it does not load at all inside iPhone Mail App, it just shows a blank email with no content at all. I have tested it using plain text version of the newsletter with just the content "Test" in the newsletter body, and it can be viewed on iPhone, but if using visual composer and just typing "Test" and no other content it still shows as a blank empty email inside iPhone Mail App. This is a massive problem as you can imagine, as many many people use iPhone and several of my clients have contacted me saying their customers are getting blank emails and thus unsubscribing. This needs to be fixed ASAP please.

**Comment by Agenda2711** [comment]
Further testing shows that composing a newsletter in Classic editor works on iPhone Mail App, but still does not work if using Visual editor. There is clearly something in the way the html code is rendered which triggers iPhone Mail App to block it entirely.

**Comment by picocodes** [comment]
Hi @Agenda2711,

This was fixed in Noptin version 3.4.0. Please send yourself a test email and check if it is rendered correctly on your end.

NOTE:- You'll have to edit your existing automated emails and click on the "**Attempt Block Recovery**" buttons in the editor.
