### ISSUE TITLE
[FEATURE] bulk edit confirmed

### ISSUE THREAD

**Issue by evolvingthoughts** [hizzle-co/noptin#850]
### Description

Is there a way to edit all my subscribers that I have imported manually from a CSV as confirmed?

### Describe the solution you'd like

A bulk edit option

**Comment by picocodes** [comment]
Hi @evolvingthoughts,

- Click on **Noptin > Subscribers**.
- Click on **Filter Records**.
- Select **Yes** in the **Confirmed** dropdown.
- Click on the **Apply Filters** button.
- Wait for Noptin to refresh the records.
- Click on the **Bulk Edit** button without selecting any subscribers. You'll be able to edit all matching subscribers.

**NOTE**: You can only bulk-edit the tags, status, source, language (if you're using WPML or Polylang), or any custom fields that have dropdown options.
