### ISSUE TITLE
Unable to save manually subscriber addition

### ISSUE THREAD

**Issue by francisfustier** [hizzle-co/noptin#871]
### Description

I can no more add manually a new subscriber as before. Once all fields are filled in, the "Save" button doesn't work and the subscriber is not added.
Regards
Francis

### Additional information

Noptin 3.4.4
WP 6.5.5
PHP 8.2

**Comment by RonnyWinkler** [comment]
I can confirm the issue with Noptin 3.4.4

**Comment by francisfustier** [comment]
> I can confirm the issue with Noptin 3.4.4

Thanks a lot, great support!
