### ISSUE TITLE
Uncaught Error: Call to undefined function wpinv_clean() after latest update

### ISSUE THREAD

**Issue by gmbhneo** [hizzle-co/noptin#89]
**Describe the bug**
After the latest update I get this error:
`
Error Details ============= An error of type E_ERROR was caused in line 27 of the file /wp-content/plugins/newsletter-optin-box/templates/settings.php. Error message: Uncaught Error: Call to undefined function wpinv_clean() in /wp-content/plugins/newsletter-optin-box/templates/settings.php:27 Stack trace: #0 /wp-content/plugins/newsletter-optin-box/includes/functions.php(845): include() #1 /wp-content/plugins/newsletter-optin-box/includes/admin/class-noptin-settings.php(46): get_noptin_template() #2 /wp-content/plugins/newsletter-optin-box/includes/admin/class-noptin-admin.php(912): Noptin_Settings::output() #3 /wp-includes/class-wp-hook.php(287): Noptin_Admin->render_settings_page() #4 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #5 /wp-includes/plugin.php(478): WP_Hook->do_action() #6/wp-admin/admin.php(259): do_action() #7 {main} thrown
`
**To Reproduce**
1. Update to the latest version
2. Go to settings page on admin panel

**Comment by picocodes** [comment]
This should be fixed now.
