### ISSUE TITLE
No new subscribers since February!

### ISSUE THREAD

**Issue by earthybirth** [hizzle-co/noptin#890]
### Description

The noptin plugin has not added any new subscribers to my list since early February, even though I know there have been plenty - I have the box at the checkout automatically enabled, and I just tried doing a mock purchase myself with the checkbox checked to add myself to the subscriber list, and nothing. any ideas why this is happening?

**Comment by picocodes** [comment]
Hi @earthybirth,

Are you using the classic WooCommerce checkout or WooCommerce checkout blocks?

**Comment by earthybirth** [comment]
Hi, am I able to get a solution for this problem?

**Comment by picocodes** [comment]
Update to the latest version of Noptin. We added support for classic checkouts using the new WooCommerce HPOS

**Comment by earthybirth** [comment]
It is already updated, and I have had auto-updates enabled since I first installed the plugin. What else can I try?

**Comment by picocodes** [comment]
Let me know what version of Noptin and WooCommerce you see when you open
the WordPress plugins page.

**Comment by earthybirth** [comment]
Woocommerce - Version 9.1.4
Noptin - Version 3.4.9

**Comment by earthybirth** [comment]
Could I please get an update on this? I really need to resolve the issue as soon as possible
