### ISSUE TITLE
Can´t change text on button

### ISSUE THREAD

**Issue by PeterKulas** [hizzle-co/noptin#916]
### Description

Hello i cant change button text. In editor it is fine but live on the page there is still submit.

### Screenshots

![image](https://github.com/user-attachments/assets/ab6ec7da-676c-4532-b19f-5672a2b7e666)
![image](https://github.com/user-attachments/assets/47727db5-188b-4dd0-bd58-3b20061f8b22)

**Comment by PeterKulas** [comment]
Also Success message doesn´t work with my own text. And it would be great if i cant change error message.

**Comment by picocodes** [comment]
Hi @PeterKulas,

We'll fix this in today's update.

**Comment by picocodes** [comment]
You can track progress for setting different error messages here:- #926
