### ISSUE TITLE
If the WP REST API is disabled, the user does not see a subscription confirmation message

### ISSUE THREAD

**Issue by mvl22** [hizzle-co/noptin#922]
### Description

More hardened Wordpress installations may have a plugin such as the [Disable WP REST API](https://wordpress.org/plugins/disable-wp-rest-api/) enabled, in order to avoid leakage of user data.

If enabled, this causes the Noptin 'Join our newsletter' form **not to show a confirmation**.

The user is correctly added to the subscribers database, but they receive no visual indication on the page that this has happened.

**Comment by picocodes** [comment]
Thanks @mvl22  this will be fixed in today's update.

**Comment by mvl22** [comment]
Thanks; I confirm this has fixed the issue.
