### ISSUE TITLE
[FEATURE] Allow subscribers to select "Interests"

### ISSUE THREAD

**Issue by scrobbleme** [hizzle-co/noptin#924]
### Description

In addition to the existing `tags`, a new subscriber-oriented taxonomy would be nice.

My preferred name is  `Interests`

**Features**:

- Subscribers can select `interests`  from their profile page
- Campaign receivers can be filtered for  `interests` 
- subscription forms can be bound to `interests`  
   - subscribers can use a subscription form to subscribe to a "new" another `interest`
      → means, if a subscriber already exists → the new `interest`  will be added to the subscriber's interests (respect double opt-in) 
- (can be pro feature)

**Use case**

Our specific use case is, that we have beside the regular monthly newsletters → event specific newsletters (for larger events).

- The events have a custom form, which adds a specific "tag"
- ❌ Problem → already existing subscribers can't use the form to "resubscribe", as they are already subscribers

**Comment by picocodes** [comment]
Hi @scrobbleme,

Most of this is already possible.

1. Click on Noptin > Settings > Custom Fields and add a new Multi-checkbox or dropdown field called "Interests".
2. Define your interests as options.
3. Subscribers will be able to select interests from their profile page.
4. You'll be able to filter campaign recipients by their interests.
5. Open any subscription forms then set the "default interests" for subscribers who sign up using the form.

> We'll work on the resubscribe feature so as to allow subscribers to subscribe to other interests.
