### ISSUE TITLE
Bonjour, formulaire d'abonnement ne s'affiche pas

### ISSUE THREAD

**Issue by Reneegasser** [hizzle-co/noptin#928]
Bonjour, mon formulaire d'abonnement ne s'affiche pas correctement. Je voulais le placer tout en bas de page, impossible et sur la colonne
![459941851_529834242979725_2286817033273589336_n](https://github.com/user-attachments/assets/fa63f0ff-b9e1-4c2c-b52a-f117d6f75e06)
![460441270_749004150685993_6190721666356462364_n](https://github.com/user-attachments/assets/5b024e88-94f9-4177-8766-db7500f0f5fa)
 de droite pareil! Que se passe t-il?

**Comment by picocodes** [comment]
Closing. This was a theme conflict and it was fixed via a support ticket.
