### ISSUE TITLE
[FEATURE] Add pre-duplicate modal

### ISSUE THREAD

**Issue by scrobbleme** [hizzle-co/noptin#938]
### Description

People just don't get that the new mail has the same name as the previous... 

To improve the workflow, it would be nice to just have a modal on duplicating a newsletter (might be nice for new mails too)

### Describe the solution you'd like

A modal which 

- ask for a new `subject` and `name` (what else?) for the new campaign. 
- with the current values + "copy" as default
   - Or maybe instead of copy some kind of counter or just the current date? 

### Screenshots

![image](https://github.com/user-attachments/assets/81c6405c-a879-4e50-b40c-73113d684719)

**Comment by picocodes** [comment]
Awesome. I am currently working on this.

**Comment by scrobbleme** [comment]
@picocodes Thanks for the new modal. It's great and really helpful 💯💯💯
