### ISSUE TITLE
Automated email campaign not processing merge tags

### ISSUE THREAD

**Issue by treehouse103** [hizzle-co/noptin#963]
### Description

I have an automated email campaign to send new post emails to all subscribers. I want the sender name and reply-to address to be the post author, not the website. (I need to keep the "send from" email the website's address so that it will work with AmazonSES.)

In the right-hand settings under "send from" I put:

> [[post_author.first_name]] [[post_author.last_name]]

And for "reply-to" I put:

> [[post_author.email]]

I save the campaign, then send a test message to myself, and it works fine.

When the campaign runs automatically, the merge tags don't work. There are two issues:
1. The "send from" shows up as the merge tags _as the name_.
2. The "reply-to" is the website email address rather than the email address that should be populated by the merge tags.

Put another way, the email should come from:

> "Joe User" <website@tld.com> <reply-to:joesuser1@gmail.com>

But instead the emails come from:

> "[[post_author.first_name]] [[post_author.last_name]]" <website@tld.com>

**Comment by picocodes** [comment]
Fix scheduled for today's update
